# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI feature

on:
  pull_request:
    branches: [ master ]

jobs:
  firebase_feature_deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v1.3.0
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy --only hosting:$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]' )
